project_id = "wshfsjbwijxlgkzfrdya"

[functions.create-admin]
verify_jwt = false

[functions.register-admin]
verify_jwt = false

[functions.submit-application]
verify_jwt = true

[functions.create-batch]
verify_jwt = true

[functions.delete-batch]
verify_jwt = true

[functions.delete-application]
verify_jwt = true

[functions.delete-all-applications]
verify_jwt = true

[functions.delete-student]
verify_jwt = true

[functions.delete-faculty]
verify_jwt = true

[functions.delete-staff]
verify_jwt = true
